import 'practice_bank.dart';
import 'course_models.dart';

const geometryLessons = [
  Lesson(
    'geo_angles',
    'Rectas y ángulos',
    'Mide los giros',
    '∠',
    'Un ángulo mide un giro en grados. Un ángulo recto mide 90°, uno llano 180° y una vuelta 360°. Los complementarios suman 90°; los suplementarios, 180°. Los ángulos opuestos por el vértice son iguales.',
    'Un ángulo mide 35°. ¿Cuánto mide su complementario?',
    [
      'Los complementarios completan un ángulo recto: 90°.',
      'Plantea 35° + x = 90°.',
      'Resta 35°: x = 55°. Comprobación: 35° + 55° = 90°.',
    ],
    [
      Exercise(
        '¿Cuál es el suplemento de 120°?',
        ['60°', '30°', '240°'],
        0,
        'Los suplementarios suman 180°.',
        '180° − 120° = 60°.',
        [
          '',
          '90° se usa para complementarios; 120° ya supera 90°.',
          '240° completa una vuelta, no un ángulo llano.',
        ],
      ),
      Exercise(
        'Dos rectas se cruzan. Un ángulo mide 48°. ¿Cuánto mide su opuesto por el vértice?',
        ['132°', '48°', '42°'],
        1,
        'Los ángulos enfrentados en el cruce tienen la misma medida.',
        'Los opuestos por el vértice son iguales: 48°.',
        [
          '132° es el ángulo adyacente, que suma 180° con 48°.',
          '',
          '42° es el complemento, no el opuesto.',
        ],
      ),
      Exercise(
        '¿Qué tipo de ángulo es uno de 125°?',
        ['Agudo', 'Recto', 'Obtuso'],
        2,
        'Compara su medida con 90° y 180°.',
        '125° está entre 90° y 180°: es obtuso.',
        ['Un agudo mide menos de 90°.', 'Un recto mide exactamente 90°.', ''],
      ),
      ...extraGeoAngles,
    ],
  ),
  Lesson(
    'geo_triangles',
    'Triángulos',
    'Tres lados, una regla',
    '△',
    'Los ángulos interiores de un triángulo suman 180°. Un equilátero tiene tres lados iguales y tres ángulos de 60°; un isósceles tiene al menos dos lados iguales. Para formar un triángulo, la suma de los dos lados menores debe superar el lado mayor.',
    'Un triángulo tiene ángulos de 50° y 60°. Halla el tercero.',
    [
      'La suma de los tres ángulos es 180°.',
      'Suma los conocidos: 50° + 60° = 110°.',
      'El tercero mide 180° − 110° = 70°.',
    ],
    [
      Exercise(
        'Dos ángulos de un triángulo miden 35° y 65°. ¿Cuánto mide el tercero?',
        ['80°', '100°', '90°'],
        0,
        'Resta la suma de los conocidos a 180°.',
        '35° + 65° = 100°; 180° − 100° = 80°.',
        [
          '',
          '100° es la suma de los dos conocidos, no el ángulo restante.',
          'No todos los triángulos tienen un ángulo recto.',
        ],
      ),
      Exercise(
        '¿Cuánto mide cada ángulo de un triángulo equilátero?',
        ['90°', '60°', '45°'],
        1,
        'Reparte 180° entre tres ángulos iguales.',
        '180° ÷ 3 = 60°.',
        [
          'Tres ángulos de 90° sumarían 270°.',
          '',
          'Tres ángulos de 45° sumarían solo 135°.',
        ],
      ),
      Exercise(
        '¿Qué longitudes pueden formar un triángulo?',
        ['2, 3 y 6 cm', '2, 3 y 5 cm', '3, 4 y 5 cm'],
        2,
        'La suma de los dos lados menores debe ser mayor que el mayor.',
        '3 + 4 = 7 > 5. Los otros grupos no cumplen la desigualdad estricta.',
        [
          '2 + 3 = 5 < 6: los lados no pueden cerrar la figura.',
          '2 + 3 = 5: la igualdad produce una línea, no un triángulo.',
          '',
        ],
      ),
      ...extraGeoTriangles,
    ],
  ),
  Lesson(
    'geo_perimeter',
    'Perímetro y área',
    'Borde o superficie',
    '▱',
    'El perímetro es la longitud del contorno: suma todos los lados. El área mide la superficie y usa unidades cuadradas. Rectángulo: A = base × altura. Triángulo: A = base × altura perpendicular ÷ 2. Paralelogramo: A = base × altura perpendicular.',
    'Un rectángulo mide 6 cm por 4 cm. Calcula su perímetro y su área.',
    [
      'Perímetro: 6 + 4 + 6 + 4 = 20 cm.',
      'Área: 6 × 4 = 24 cm².',
      'El borde se mide en cm; la superficie, en cm².',
    ],
    [
      Exercise(
        'Un rectángulo mide 8 cm por 3 cm. ¿Cuál es su perímetro?',
        ['24 cm', '11 cm', '22 cm'],
        2,
        'Cuenta dos lados de cada longitud.',
        'P = 2 × (8 + 3) = 22 cm.',
        [
          '8 × 3 calcula el área: 24 cm².',
          '11 cm suma solo dos de los cuatro lados.',
          '',
        ],
      ),
      Exercise(
        'Un triángulo tiene base de 10 cm y altura perpendicular de 6 cm. ¿Cuál es su área?',
        ['30 cm²', '60 cm²', '16 cm²'],
        0,
        'Multiplica base por altura y divide entre dos.',
        'A = 10 × 6 ÷ 2 = 30 cm².',
        [
          '',
          'Falta dividir entre dos: un triángulo ocupa la mitad del rectángulo correspondiente.',
          'Sumar base y altura no calcula una superficie.',
        ],
      ),
      Exercise(
        'Un paralelogramo tiene base de 7 cm y altura perpendicular de 4 cm. ¿Cuál es su área?',
        ['14 cm²', '28 cm²', '22 cm²'],
        1,
        'Usa la altura perpendicular, no un lado inclinado.',
        'A = 7 × 4 = 28 cm².',
        [
          'Dividir entre dos corresponde al triángulo.',
          '',
          '2 × (7 + 4) no es la fórmula del área.',
        ],
      ),
      ...extraGeoPerimeter,
    ],
  ),
  Lesson(
    'geo_circle',
    'Circunferencia y círculo',
    'Una vuelta alrededor de π',
    '○',
    'El radio r va del centro al borde; el diámetro d atraviesa el centro y vale 2r. La longitud de la circunferencia es C = 2πr = πd. El área del círculo es A = πr². Conserva π para un resultado exacto o usa la aproximación indicada.',
    'Un círculo tiene radio de 3 cm. Halla su área exacta.',
    [
      'Usa A = πr².',
      'Eleva el radio al cuadrado: 3² = 9.',
      'A = 9π cm². La circunferencia, en cambio, mide 6π cm.',
    ],
    [
      Exercise(
        'Un círculo tiene radio de 5 cm. ¿Cuál es su diámetro?',
        ['10 cm', '2,5 cm', '25 cm'],
        0,
        'El diámetro equivale a dos radios.',
        'd = 2 × 5 = 10 cm.',
        [
          '',
          'Dividir entre dos convierte un diámetro en radio, al revés de lo pedido.',
          '25 es el radio al cuadrado, no una longitud del diámetro.',
        ],
      ),
      Exercise(
        'Un círculo tiene radio de 4 cm. ¿Cuál es su área exacta?',
        ['8π cm²', '16π cm²', '4π cm²'],
        1,
        'El área usa el cuadrado del radio.',
        'A = π × 4² = 16π cm².',
        [
          '8π corresponde a la longitud de la circunferencia, en cm.',
          '',
          'Falta elevar 4 al cuadrado.',
        ],
      ),
      Exercise(
        'Un círculo tiene diámetro de 10 cm. Usa π ≈ 3,14. ¿Cuánto mide su circunferencia?',
        ['62,8 cm', '78,5 cm', '31,4 cm'],
        2,
        'Con el diámetro conocido, usa C = πd.',
        'C ≈ 3,14 × 10 = 31,4 cm.',
        [
          '10 es el diámetro, no el radio; no lo multipliques otra vez por dos.',
          '78,5 cm² es el área usando radio de 5 cm.',
          '',
        ],
      ),
      ...extraGeoCircle,
    ],
  ),
  Lesson(
    'geo_pythagoras',
    'Teorema de Pitágoras',
    'Encuentra el lado que falta',
    '√',
    'En un triángulo rectángulo, los catetos a y b forman el ángulo de 90° y la hipotenusa c está enfrente. Se cumple a² + b² = c². Para hallar un cateto, resta los cuadrados. Al final toma la raíz cuadrada. Este teorema requiere un ángulo recto.',
    'Los catetos miden 3 cm y 4 cm. Halla la hipotenusa.',
    [
      'c² = 3² + 4² = 9 + 16.',
      'c² = 25; toma la raíz positiva.',
      'c = 5 cm. Comprueba: 9 + 16 = 25.',
    ],
    [
      Exercise(
        'Los catetos de un triángulo rectángulo miden 6 y 8 cm. ¿Cuánto mide la hipotenusa?',
        ['14 cm', '10 cm', '100 cm'],
        1,
        'Suma los cuadrados y toma la raíz.',
        'c = √(6² + 8²) = √100 = 10 cm.',
        [
          'No se suman directamente las longitudes de los catetos.',
          '',
          '100 es c²; falta tomar la raíz cuadrada.',
        ],
      ),
      Exercise(
        'La hipotenusa mide 13 cm y un cateto 5 cm. ¿Cuánto mide el otro cateto?',
        ['12 cm', '8 cm', '√194 cm'],
        0,
        'El cuadrado del cateto es 13² − 5².',
        'b = √(169 − 25) = √144 = 12 cm.',
        [
          '',
          'Restar las longitudes no equivale a restar sus cuadrados.',
          'Debes restar 5² de 13², no sumarlos.',
        ],
      ),
      Exercise(
        '¿Qué lados forman un triángulo rectángulo?',
        ['4, 5 y 6 cm', '3, 4 y 6 cm', '5, 12 y 13 cm'],
        2,
        'El mayor lado debe cumplir c² = a² + b².',
        '5² + 12² = 25 + 144 = 169 = 13².',
        ['4² + 5² = 41, pero 6² = 36.', '3² + 4² = 25, pero 6² = 36.', ''],
      ),
      ...extraGeoPythagoras,
    ],
  ),
  Lesson(
    'geo_solids',
    'Cuerpos y volumen',
    'Del plano al espacio',
    '▣',
    'El volumen mide el espacio ocupado y usa unidades cúbicas. Prisma rectangular: V = largo × ancho × alto. Cubo: V = lado³. Cilindro: V = πr²h, donde r es el radio de la base y h su altura. El área de superficie y el volumen son medidas diferentes.',
    'Una caja mide 5 cm de largo, 3 cm de ancho y 2 cm de alto.',
    [
      'Su base tiene área 5 × 3 = 15 cm².',
      'Multiplica por la altura: 15 × 2 = 30.',
      'El volumen es 30 cm³; las tres dimensiones producen unidades cúbicas.',
    ],
    [
      Exercise(
        'Un cubo tiene lado de 3 cm. ¿Cuál es su volumen?',
        ['9 cm³', '27 cm³', '18 cm³'],
        1,
        'Multiplica el lado por sí mismo tres veces.',
        'V = 3³ = 3 × 3 × 3 = 27 cm³.',
        [
          '9 cm² es el área de una cara; falta una dimensión.',
          '',
          'No se obtiene el volumen multiplicando el lado por seis.',
        ],
      ),
      Exercise(
        'Una caja mide 4 × 2 × 5 cm. ¿Cuál es su volumen?',
        ['40 cm³', '11 cm³', '20 cm³'],
        0,
        'Multiplica las tres dimensiones.',
        'V = 4 × 2 × 5 = 40 cm³.',
        [
          '',
          'Sumar las dimensiones no calcula el volumen.',
          '4 × 5 omite el ancho de 2 cm.',
        ],
      ),
      Exercise(
        'Un cilindro tiene radio de 2 cm y altura de 3 cm. ¿Cuál es su volumen exacto?',
        ['6π cm³', '24π cm³', '12π cm³'],
        2,
        'Calcula πr² y luego multiplica por h.',
        'V = π × 2² × 3 = 12π cm³.',
        [
          'Falta elevar el radio al cuadrado.',
          'No necesitas un factor dos adicional.',
          '',
        ],
      ),
      ...extraGeoSolids,
    ],
  ),
];
