/// Authored teaching notes, rather than stage names inserted in generic lines.
/// The visual reaction and its gestures are supplied by the existing pose system.
class StageScript {
  const StageScript(
    this.pitfall,
    this.check,
    this.kurisu,
    this.yuno,
    this.kotoko,
    this.hakari,
    this.karane,
  );
  final String pitfall, check, kurisu, yuno, kotoko, hakari, karane;
  String forTutor(String id) => switch (id) {
    'kurisu' => kurisu,
    'yuno' => yuno,
    'kotoko' => kotoko,
    'hakari' => hakari,
    'karane' => karane,
    _ => '',
  };
}

const stageScripts = <String, StageScript>{
  'operations': StageScript(
    'Las operaciones del mismo nivel se resuelven de izquierda a derecha.',
    'Comprueba primero los paréntesis y luego la prioridad de cada operación.',
    'Okabe puede poner nombres dramáticos a una operación; no puede cambiar la prioridad de la multiplicación.',
    'En mi diario escribiría cada operación en orden. Una predicción no sirve si saltas los paréntesis, Yukki.',
    'Como un episodio de Kiramon: si cambias el orden de las escenas, cambia lo que entiendes. Aquí la multiplicación tiene su turno.',
    'Mi plan con Karane empieza por los paréntesis. No mezclamos pasos: una cuenta clara se puede comprobar. ♡',
    '¡No sumes por impulso! Rentarou puede animarnos, pero primero toca comprobar qué operación tiene prioridad.',
  ),
  'variables': StageScript(
    'Una letra representa un valor; 3x significa multiplicar, no sumar 3 y x.',
    'Sustituye la letra conservando todos los signos y vuelve a evaluar.',
    'Daru llamaría a esto guardar un dato. La letra no es un adorno: cuando sustituyes, la operación sigue allí.',
    'Yukki, esta letra no predice nada: guarda un número. Podemos escribir su valor y comprobar qué produce.',
    'Takuya tiene nombres para sus personajes favoritos; aquí x es el nombre de un valor. ¡Ahora hagamos la sustitución!',
    'Mi estrategia empieza por saber qué valor tiene la letra. Karane puede ayudarme a revisar si sustituimos en todos los lugares.',
    '¡La x no se pierde al leer deprisa! Cambia cada aparición por el valor dado y después opera, como quedamos con Hakari.',
  ),
  'expressions': StageScript(
    'Solo se reúnen términos con la misma parte literal y los mismos exponentes.',
    'Comprueba que cada término reunido conserve su variable y exponente.',
    'En el laboratorio no mezclamos datos de magnitudes distintas. Tampoco juntes x con x² solo porque se parecen.',
    'En el diario pondría los términos semejantes en la misma línea. Yukki, los que tienen otra potencia necesitan su propia línea.',
    '¡Agrupemos el elenco! Takuya puede juntar personajes favoritos; nosotros juntamos coeficientes cuando la parte literal coincide.',
    'Karane, tenemos un plan de grupos: las x con las x y las x² con las x². Las letras distintas no se suman como si fueran iguales.',
    '¡Mira los exponentes antes de juntar nada! Hakari puede sonreír todo lo que quiera: x y x² siguen siendo términos distintos.',
  ),
  'equations': StageScript(
    'Una transformación debe aplicarse a ambos lados de la igualdad.',
    'Sustituye la solución en la ecuación original y verifica ambos lados.',
    'Okabe llamaría a esto equilibrio de mundos. Yo lo llamo hacer la misma operación a ambos lados y verificar el resultado.',
    'La solución es una predicción comprobable: la devuelves a la ecuación y miras si los dos lados coinciden, Yukki.',
    'Kei, ayúdame a mirar la balanza: lo que hacemos a un lado se hace al otro. ¡Así despejamos sin romperla!',
    'El plan no es mover números por arte de magia. Rentarou también tendría que mantener la igualdad y comprobar la solución.',
    '¡No cambies solo un lado! La igualdad debe sobrevivir a cada paso. Sí, Hakari, también voy a revisar la respuesta final.',
  ),
  'powers': StageScript(
    'Un exponente cuenta factores; multiplicar por el exponente no equivale a elevar.',
    'Expande una potencia pequeña para comprobar la regla que aplicaste.',
    'Daru puede escribir una multiplicación repetida con una potencia. Eso no convierte 3² en 3·2.',
    'Cada factor ocupa una página repetida de mi diario. Yukki, el exponente dice cuántas veces multiplicamos la base.',
    'Una evolución de Kiramon cambia su forma; una potencia cambia el valor por multiplicación repetida. ¡No confundas el exponente con un multiplicador!',
    'Mi plan tiene factores repetidos, no una suma secreta. Karane y yo podemos desplegar la potencia para comprobarla.',
    '¡La base y el exponente hacen trabajos distintos! Escribe los factores si hace falta; no te voy a cobrar por usar los apuntes.',
  ),
  'polynomials': StageScript(
    'La distributiva debe multiplicar cada término, respetando los signos.',
    'Desarrolla y reúne términos semejantes; comprueba con un valor sencillo.',
    'El experimento distribuye cada factor a cada término. Daru puede automatizarlo después; primero quiero ver todos los productos.',
    'Mi diario necesita una entrada para cada producto. Si olvidas uno, Yukki, la predicción del polinomio cambia.',
    '¡Nadie queda fuera del reparto! Cada término recibe su multiplicación antes de que Kei y yo juntemos los semejantes.',
    'Tengo un plan para que ningún término se quede sin pareja: distribuimos, revisamos signos y luego agrupamos.',
    '¡Ese signo menos también se distribuye! Hakari, anótalo grande para que no se nos esconda entre los términos.',
  ),
  'factoring': StageScript(
    'Una factorización debe reconstruir todos los términos del polinomio original.',
    'Multiplica los factores de nuevo y compara con la expresión original.',
    'Estamos desmontando el resultado del experimento. Si los factores son correctos, volver a multiplicarlos reconstruye el polinomio.',
    'Leer la página al revés no basta, Yukki: los factores tienen que producir exactamente la expresión que teníamos.',
    'Takuya puede resumir un episodio; nosotros escribimos un polinomio como producto. ¡Luego lo desarrollamos para comprobar el resumen!',
    'El plan va en sentido inverso: buscamos piezas que reconstruyan la expresión. Karane revisará que no falte ningún factor.',
    '¡No celebres antes de multiplicar otra vez! Si los factores no reconstruyen lo mismo, todavía queda un signo por revisar.',
  ),
  'geo_angles': StageScript(
    'Complementarios suman 90°; suplementarios suman 180°.',
    'Suma los ángulos del par y verifica qué giro deben completar.',
    'En el laboratorio medimos el giro, no el aspecto del dibujo. Distingue completar un ángulo recto de completar uno llano.',
    'Yukki, marcaría en el diario si la pareja suma 90° o 180°. Eso dice más que cómo se ve el dibujo.',
    'Kei, hagamos el giro con la mano: cuarto de vuelta o media vuelta. ¡Así recordamos qué suma pide el problema!',
    'Mi estrategia es escribir la suma que falta antes de restar. Karane, 90° y 180° tienen planes distintos.',
    '¡No elijas 90° solo porque dos líneas se ven bonitas juntas! Lee qué relación tienen los ángulos.',
  ),
  'geo_triangles': StageScript(
    'Los ángulos interiores de un triángulo suman 180°; sus lados deben cumplir la desigualdad triangular.',
    'Verifica la suma de ángulos o que cada lado sea menor que la suma de los otros dos.',
    'Tres medidas no garantizan un triángulo. En el laboratorio comprobamos la desigualdad antes de dar la figura por construida.',
    'Yukki, una predicción de tres lados puede fallar si no llegan a cerrar. Comprueba que dos juntos superen al tercero.',
    '¡Que el equipo cierre la figura! Los tres ángulos tienen que completar 180°, aunque el dibujo de Takuya esté torcido.',
    'Mi plan tiene tres esquinas y una suma fija. Si una medida falta, Karane y yo la recuperamos de los 180°.',
    '¡La figura tiene que poder existir! Antes de calcular, revisa si esos tres lados pueden cerrar un triángulo.',
  ),
  'geo_perimeter': StageScript(
    'El perímetro mide el borde y el área la superficie; sus unidades son distintas.',
    'Comprueba si la respuesta debe expresarse en unidades simples o cuadradas.',
    'Okabe puede recorrer el borde del laboratorio; cubrir su suelo es otra medida. No confundas perímetro y área.',
    'Yukki, rodear la página no es llenar la página. En el diario anotaría longitud para el borde y cuadrados para la superficie.',
    'Kei, ¿estamos poniendo una cinta alrededor o cubriendo con papel? ¡Esa imagen ayuda a elegir perímetro o área!',
    'El plan primero pregunta qué medimos. Para rodear sumamos longitudes; para cubrir calculamos superficie.',
    '¡Mira las unidades! Si piden superficie, una respuesta en centímetros solos todavía no describe el área.',
  ),
  'geo_circle': StageScript(
    'El diámetro es dos radios; circunferencia y área usan fórmulas distintas.',
    'Identifica radio y diámetro antes de sustituir; distingue 2πr de πr².',
    'La taza de café del laboratorio tiene borde y superficie. Uno usa r; la otra usa r². El dato llamado diámetro hay que dividirlo entre dos.',
    'Dibujaría un radio en el diario, Yukki. Así no confundimos la distancia al centro con la que cruza todo el círculo.',
    '¡Kiramon podría dar vueltas al borde! Pero cubrir el círculo es otro reto. Kei, primero dime si tenemos radio o diámetro.',
    'Mi estrategia evita una trampa: si el dato atraviesa todo el círculo, es diámetro. Karane revisa que usemos la mitad como radio.',
    '¡No metas el diámetro donde pide r! Hakari, marca el centro; desde ahí medimos el radio y elegimos la fórmula.',
  ),
  'geo_pythagoras': StageScript(
    'Pitágoras solo aplica a un triángulo rectángulo; la hipotenusa está frente al ángulo recto.',
    'Vuelve a elevar los lados al cuadrado y verifica a²+b²=c².',
    'Una medición diagonal no se obtiene sumando lados. Comprueba el ángulo recto, suma cuadrados y al final toma la raíz.',
    'Yukki, anotaría cuál lado está frente a 90° antes de predecir su longitud. Esa es la hipotenusa.',
    '¡La diagonal es el camino del episodio! Takuya puede dibujarla, pero nosotros necesitamos cuadrados y una raíz, no sumar longitudes.',
    'Si buscamos un cateto, el plan resta su cuadrado del de la hipotenusa. No siempre toca sumar, Karane.',
    '¡La hipotenusa no puede salir más corta que un cateto! Esa comprobación rápida nos puede avisar de un error.',
  ),
  'geo_solids': StageScript(
    'Volumen usa unidades cúbicas; un área de base se multiplica por una altura perpendicular.',
    'Comprueba la fórmula del sólido y escribe unidades cúbicas para el volumen.',
    'Para medir la capacidad de una caja del laboratorio necesitamos tres dimensiones. El área de una cara todavía no es el volumen.',
    'Yukki, un dibujo ocupa una página, pero una caja ocupa espacio. En el diario pondría unidades cúbicas para esa capacidad.',
    'Kei, imaginemos apilar capas: área de base por altura. ¡Es otra dimensión añadida al dibujo!',
    'El plan llena el sólido por capas. Karane y yo revisaremos que la altura sea perpendicular a la base.',
    '¡No te quedes en el área! Para el volumen falta la tercera dimensión y una unidad cúbica al final.',
  ),
  'trig_sides': StageScript(
    'Opuesto y adyacente dependen del ángulo elegido; la hipotenusa no cambia.',
    'Marca el ángulo de referencia y vuelve a nombrar los lados desde él.',
    'Cambiar el ángulo de observación cambia qué cateto llamas opuesto. La hipotenusa sigue frente a 90°, incluso si Okabe gira el dibujo.',
    'Yukki, primero marcaría el ángulo en el diario. Desde ese punto podemos decir qué lado está enfrente y cuál al lado.',
    '¡Cambiamos la cámara del episodio! Desde otro ángulo se intercambian los catetos, pero Kei reconoce la misma hipotenusa.',
    'El plan empieza por el ángulo de referencia. Sin él, Karane y yo no podemos llamar opuesto a un cateto con seguridad.',
    '¡Girar el teléfono no cambia la hipotenusa! Mira el ángulo recto y después el ángulo que pide el problema.',
  ),
  'trig_ratios': StageScript(
    'Seno, coseno y tangente relacionan pares distintos de lados.',
    'Escribe los nombres de los dos lados del cociente antes de calcular.',
    'Quiero el cociente correcto: seno usa opuesto sobre hipotenusa; coseno, adyacente sobre hipotenusa. Daru no puede arreglar una etiqueta equivocada.',
    'Yukki, una razón necesita numerador y denominador correctos. En el diario guardaría los nombres antes de los números.',
    '¡Cada razón tiene su reparto! Kei me ayuda a señalar los dos lados que usa el seno, el coseno o la tangente.',
    'Mi estrategia elige la razón según los lados que conocemos y el que buscamos. Así no adivinamos una fórmula por su nombre.',
    '¡No inviertas el cociente por prisa! Opuesto sobre adyacente es tangente, no adyacente sobre opuesto.',
  ),
  'trig_radians': StageScript(
    'Una vuelta completa equivale a 360° y a 2π radianes.',
    'Comprueba la conversión con la referencia 180°=π radianes.',
    'El giro no cambia al cambiar de unidad. Okabe puede llamarlo otra cosa; 180° siguen siendo π radianes.',
    'Yukki, el diario puede escribir el mismo giro en dos unidades. Hay que convertir la medida, no cambiar el ángulo.',
    '¡Un episodio puede tener dos idiomas y el mismo final! Aquí 360° y 2π describen la misma vuelta.',
    'El plan de conversión multiplica por π/180 o por 180/π. Karane revisa qué unidad queremos al final.',
    '¡No pegues el símbolo de grados a una medida en radianes! Primero convierte y después escribe la unidad correcta.',
  ),
  'trig_special': StageScript(
    'Los triángulos 45°–45°–90° y 30°–60°–90° tienen proporciones diferentes.',
    'Reconstruye la proporción del triángulo notable y el cociente que pide la razón.',
    'Podemos obtener valores exactos sin una calculadora del laboratorio. Primero distingue el triángulo isósceles del de 30° y 60°.',
    'Yukki, guardaría las proporciones en una página pequeña del diario. Una raíz exacta no tiene que convertirse en decimal.',
    '¡Dos equipos de lados distintos! Kei reconoce 1,1,√2 y 1,√3,2; ahora elige el que corresponde al ángulo.',
    'Mi plan conserva las raíces para que la respuesta sea exacta. Karane, no cambiemos √3 por una aproximación si no la piden.',
    '¡El lado de 60° no es el mismo que el de 30°! Mira cuál está enfrente antes de escribir el cociente.',
  ),
  'trig_circle': StageScript(
    'Los signos de seno y coseno dependen del cuadrante y las coordenadas del punto.',
    'Comprueba el cuadrante y que cos²θ+sin²θ=1.',
    'El punto del círculo tiene coordenadas coseno y seno. En el laboratorio compruebo el cuadrante antes de confiar en un signo.',
    'Yukki, dar una vuelta completa nos devuelve al mismo punto del diario. El signo lo decide dónde termina el giro.',
    '¡Kiramon podría recorrer todo el círculo! Nosotros seguimos su posición: x es coseno e y es seno.',
    'El plan usa el ángulo de referencia y luego ajusta signos. Karane, en el segundo cuadrante el seno queda positivo.',
    '¡No copies ambos signos del primer cuadrante! Mira dónde está el punto y verifica la identidad del círculo.',
  ),
  'trig_applications': StageScript(
    'El ángulo y los lados conocidos determinan la razón; en alturas puede faltar sumar la altura del observador.',
    'Comprueba el dibujo, la razón elegida y qué altura representa el resultado.',
    'Una altura medida desde nuestros ojos no es todavía la altura total. El laboratorio necesita definir desde dónde empieza cada longitud.',
    'Yukki, dibujaría la línea de visión antes de predecir la altura. Así vemos si falta sumar la altura de quien observa.',
    '¡Kei hace de cámara y Takuya de observador! Marcamos el ángulo, nombramos los lados y elegimos la razón que necesita la escena.',
    'Mi estrategia dibuja el triángulo antes de despejar. Karane puede comprobar si el resultado mide una diferencia de alturas o la altura completa.',
    '¡No uses seno solo porque te suena! Si tienes opuesto y adyacente, la tangente puede ser la que necesitamos.',
  ),
  'logarithms': StageScript(
    'Un logaritmo real exige argumento positivo y base positiva distinta de uno.',
    'Convierte la respuesta a una potencia y comprueba las condiciones originales.',
    'Daru conoce la salida de la potencia y busca el exponente. Eso hace el logaritmo; no devuelve el argumento por cortesía.',
    'Yukki, la predicción busca cuántas veces crece la base, pero el argumento debe ser positivo. Esa condición va primero en el diario.',
    '¡Buscamos el nivel de evolución! Takuya conoce el resultado; nosotros buscamos el exponente y lo comprobamos elevando la base.',
    'Mi plan deshace una potencia. Karane, comprobamos el argumento antes de usar reglas de productos o cocientes.',
    '¡El logaritmo no se reparte sobre una suma! Hakari, mejor volvamos a la definición antes de inventar una regla.',
  ),
  'advanced_powers': StageScript(
    'Exponentes negativos producen recíprocos y las leyes de cocientes exigen base no nula.',
    'Verifica el signo, las restricciones de la base y la regla del exponente utilizada.',
    'Un exponente negativo no vuelve negativa la base: produce un recíproco. Ese experimento exige una base distinta de cero.',
    'Yukki, si la potencia aparece invertida, el diario puede escribirla como recíproco. El signo de la base se estudia aparte.',
    '¡No confundamos bajar un nivel con cambiar de signo! Un exponente negativo invierte la potencia; Kei revisa la base.',
    'El plan distingue producto, cociente y potencia de potencia. Karane no me dejaría sumar exponentes cuando toca multiplicarlos.',
    '¡Si divides, comprueba que la base no sea cero! Las reglas también tienen condiciones, aunque el resultado parezca fácil.',
  ),
  'quadratics': StageScript(
    'La raíz cuadrada aporta dos signos cuando corresponden; el discriminante decide las raíces reales.',
    'Sustituye cada raíz y descarta las que incumplan el dominio físico del problema.',
    'El discriminante es nuestro primer diagnóstico de laboratorio. Después probamos cada raíz; no escondas la segunda solución.',
    'Yukki, esta página puede tener dos finales válidos. Los comprobamos en la ecuación, y en una medida física rechazamos la longitud negativa.',
    '¡A veces el episodio tiene dos caminos! Kei y yo revisamos ambas raíces antes de decidir cuáles tienen sentido en el problema.',
    'Mi estrategia primero elige factorizar o usar la fórmula general. Karane, los dos signos también forman parte del plan.',
    '¡No borres una raíz porque no te gusta su signo! Comprueba las dos; solo el contexto puede excluir una solución matemática.',
  ),
  'pre_functions': StageScript(
    'Raíces reales y denominadores imponen restricciones diferentes al dominio.',
    'Prueba un valor permitido y comprueba que los valores excluidos realmente incumplan una condición.',
    'El dominio es la lista de entradas admisibles del experimento. Okabe no puede declarar válida una división por cero.',
    'Yukki, una predicción solo existe para entradas permitidas. En mi diario separo raíz real y denominador no nulo.',
    '¡El personaje tiene reglas de entrada! Takuya puede dar cualquier nombre a x, pero la función necesita valores de su dominio.',
    'Mi plan tiene dos filtros: que la raíz exista y que el denominador no se anule. Karane revisa si debemos aplicar ambos.',
    '¡Que la raíz de cero exista no significa que puedas dividir entre ella! Esa diferencia cambia el dominio.',
  ),
  'pre_inequalities': StageScript(
    'Multiplicar por negativo invierte la desigualdad; un valor absoluto describe una distancia.',
    'Comprueba un valor interior y revisa si los extremos se incluyen.',
    'En el laboratorio, cambiar el signo invierte el orden. Okabe puede protestar; dividir una desigualdad por un negativo obliga a invertirla.',
    'Yukki, |x−h| es distancia al centro, no una instrucción para borrar signos. El diario puede marcar regiones interiores o exteriores.',
    '¡Kei, dibuja la recta! Un intervalo interior es un tramo; la región exterior tiene dos caminos distintos.',
    'Mi estrategia prueba un número del intervalo antes de darlo por bueno. Karane también revisa si los extremos entran.',
    '¡Si dividiste por −2, cambia el sentido! El intervalo no se arregla ignorando el signo del coeficiente.',
  ),
  'pre_transformations': StageScript(
    'El signo del desplazamiento horizontal se interpreta dentro del argumento; la reflexión no cambia la amplitud.',
    'Ubica el vértice y comprueba una altura a cada lado de él.',
    'El laboratorio sigue el vértice: en (x−h)²+v está en (h,v). No dejaré que Okabe confunda el signo interno con el desplazamiento.',
    'Yukki, cambiar la posición de la curva no cambia la regla del cuadrado. El diario puede anotar primero su nuevo vértice.',
    '¡Movemos el escenario, no improvisamos el dibujo! Kei marca el vértice y yo miro si la parábola abre arriba o abajo.',
    'Mi plan separa traslación, escala y reflexión. Karane puede comparar las alturas sin mezclar esos tres cambios.',
    '¡Un signo menos fuera del cuadrado hace que abra abajo! Uno dentro puede indicar otro desplazamiento.',
  ),
  'pre_composition': StageScript(
    'La función interior actúa primero; una inversa requiere un dominio adecuado.',
    'Comprueba la composición en orden y verifica que la inversa devuelva la entrada permitida.',
    'Daru encadenaría dos programas: primero g y después f. La composición no promete el mismo resultado al invertir ese orden.',
    'Yukki, la salida de una página se vuelve la entrada de la siguiente. Para deshacerlas necesitamos una inversa bien definida.',
    '¡Primero una escena y luego la otra! Takuya sabe que cambiarlas altera la trama; aquí cambia f(g(x)).',
    'Mi estrategia recupera la entrada con la inversa. Karane, si usamos un cuadrado debemos decidir qué rama corresponde al dominio.',
    '¡f^(-1) no significa 1/f! Es la función que deshace el proceso, y no siempre existe sin restringir el dominio.',
  ),
  'pre_polynomials': StageScript(
    'Una raíz anula el polinomio; el residuo en una división lineal es un valor de P.',
    'Evalúa el polinomio en la raíz o en el punto del divisor para comprobar.',
    'El laboratorio prueba P(r): si da cero, x−r es factor. La multiplicidad nos cuenta si la gráfica cruza o solo toca el eje.',
    'Yukki, una raíz marca dónde la página da cero. El residuo es otra pregunta: evalúa en el punto del divisor.',
    '¡Dos escenas en el eje! Una raíz par toca y una impar cruza. Kei puede comprobar el cambio de signo alrededor.',
    'Mi plan combina raíces y coeficientes, pero luego vuelve a evaluar. Karane no aceptaría una raíz que no anule P.',
    '¡No llames raíz a cualquier residuo! Una raíz exige P(r)=0; el residuo puede ser distinto de cero.',
  ),
  'pre_rational': StageScript(
    'Cancelar un factor no devuelve al dominio una entrada excluida.',
    'Revisa el denominador original y distingue hueco, polo y comportamiento lejano.',
    'La simplificación no borra la historia del experimento. Un factor cancelado puede dejar un hueco del dominio original.',
    'Yukki, aunque la página se simplifique, guardo sus entradas prohibidas. Un hueco no se convierte en un punto válido por cambiar la escritura.',
    '¡No borremos una escena prohibida al editar! Takuya, el denominador original sigue indicando dónde hay que mirar.',
    'Mi plan separa el hueco del polo antes de leer asíntotas. Karane compara qué factores se cancelaron y cuáles quedaron.',
    '¡Primero escribe las exclusiones! Si cancelas y después olvidas el denominador original, el dominio cambia sin permiso.',
  ),
  'pre_exp_log': StageScript(
    'El factor inicial y la razón de crecimiento cumplen papeles distintos; los logaritmos conservan su dominio.',
    'Sustituye el tiempo calculado en el modelo y verifica el argumento del logaritmo.',
    'En el laboratorio un modelo C·b^t tiene condición inicial y razón. No mezcles el primer valor con el ritmo del crecimiento.',
    'Yukki, el diario puede predecir una cantidad futura usando un modelo, pero comprobamos el tiempo en la fórmula original.',
    '¡El cultivo sube por un factor cada turno! Como un modelo de niveles para Takuya, pero el exponente cuenta el tiempo.',
    'El plan despeja el tiempo deshaciendo la potencia. Karane, antes de usar un logaritmo revisamos sus argumentos.',
    '¡Duplicarse tres veces no es multiplicar por tres! Usa la potencia y conserva la cantidad inicial.',
  ),
  'pre_unit_circle': StageScript(
    'Las vueltas completas no cambian el punto; los signos dependen del cuadrante final.',
    'Reduce vueltas y comprueba el ángulo de referencia y la identidad del círculo.',
    'El experimento vuelve al mismo punto cada 2π. Okabe no necesita otra línea temporal para repetir seno y coseno.',
    'Yukki, una vuelta completa devuelve la predicción a la misma posición del círculo. El diario aún debe comprobar el cuadrante final.',
    '¡Nuestro personaje vuelve al mismo escenario tras 2π! Kei mira si la coordenada horizontal o vertical cambia de signo.',
    'Mi estrategia quita vueltas completas y después usa el ángulo notable. Karane revisa el signo antes de celebrar.',
    '¡No cambies el signo solo porque el ángulo es grande! Reduce las vueltas y mira dónde termina.',
  ),
  'pre_trig_analysis': StageScript(
    'Una ecuación periódica necesita todas las soluciones del intervalo; amplitud y período son medidas distintas.',
    'Sustituye cada ángulo y revisa los extremos del intervalo pedido.',
    'Daru puede muestrear una onda; la amplitud mide altura y el período repetición. Para resolver, quiero todas las soluciones del intervalo.',
    'Yukki, una predicción puede repetirse en varias posiciones. El diario debe listar todos los ángulos válidos, no quedarse con el primero.',
    '¡El episodio se repite, pero no a cualquier ritmo! Kei distingue la altura de la onda del tiempo que tarda en repetirse.',
    'El plan considera ambos signos cuando sacamos raíz de cos²x. Karane puede comprobar cada ángulo en la ecuación original.',
    '¡Si hay un cuadrado, no te quedes solo con la raíz positiva! Y revisa si el intervalo incluye el extremo final.',
  ),
  'pre_conics': StageScript(
    'Los denominadores son cuadrados de semiejes; elipse e hipérbola usan relaciones focales distintas.',
    'Comprueba el centro, los semiejes y si corresponde sumar o restar sus cuadrados.',
    'En el laboratorio clasificamos la ecuación antes de buscar el foco. La elipse resta cuadrados; la hipérbola los suma.',
    'Yukki, primero anoto el tipo de curva en el diario. Un foco de parábola no se obtiene con la fórmula de una elipse.',
    '¡Cuatro escenarios curvos! Kei mira los signos: círculo, elipse, parábola e hipérbola tienen guiones distintos.',
    'Mi plan toma raíces de los denominadores para recuperar los semiejes. Karane, el número escrito abajo no es ya la longitud.',
    '¡Lee el tipo de cónica antes de usar c²! En una hipérbola se suman a² y b²; en una elipse se restan.',
  ),
  'pre_parametric': StageScript(
    'Eliminar el parámetro no elimina sus restricciones; el radio polar puede ser negativo.',
    'Sustituye el mismo parámetro en ambas coordenadas y conserva su intervalo permitido.',
    'El laboratorio describe un movimiento con t. Al eliminarlo, no podemos permitir puntos que la parametrización original nunca visita.',
    'Yukki, cada instante del diario produce x e y juntos. No mezcles una coordenada de un instante con otra del siguiente.',
    '¡La cámara sigue el parámetro! Kei convierte radio y ángulo a dos coordenadas sin perder el sentido de la dirección.',
    'Mi estrategia usa x=r cos θ e y=r sin θ aunque r sea negativo. Karane comprueba hacia qué lado apunta entonces.',
    '¡La restricción t≥0 también se transforma al despejar! No declares toda la parábola si solo recorrimos la mitad.',
  ),
  'pre_sequences': StageScript(
    'El término n usa n−1 saltos desde el primero; una serie geométrica infinita exige |r|<1.',
    'Cuenta términos y comprueba diferencia, razón o condición de convergencia.',
    'Daru distinguiría incrementar y multiplicar. La diferencia aritmética no es la razón geométrica, y una suma infinita requiere convergencia.',
    'Yukki, la primera página ya es a₁. Para llegar a la quinta hacemos cuatro saltos, no cinco.',
    '¡Cada episodio puede sumar o multiplicar al anterior! Takuya, primero identifiquemos cuál de las dos reglas sigue la sucesión.',
    'Mi plan cuenta el primer término antes de aplicar la suma. Karane revisa que una serie infinita tenga |r| menor que uno.',
    '¡No uses a₁rⁿ si estás contando desde n=1! El exponente correcto cuenta los saltos que faltan desde el primero.',
  ),
  'pre_counting': StageScript(
    'El orden importa en cargos distintos; sin reemplazo cambia el total de la segunda extracción.',
    'Comprueba qué resultados son distintos y que la probabilidad quede entre cero y uno.',
    'El laboratorio cuenta resultados, no nombres bonitos. Dos cargos distintos hacen que el orden importe; un equipo sin cargos no.',
    'Yukki, después de sacar una ficha el diario tiene menos posibilidades. La segunda probabilidad no conserva el mismo total.',
    '¡Kei y Takuya pueden intercambiar cargos y crear otra asignación! Pero si solo forman un equipo, no lo contamos dos veces.',
    'Mi estrategia decide primero si el orden importa. Después, Karane y yo contamos sin repetir casos.',
    '¡Sin reemplazo significa que la ficha no vuelve! Reduce favorables y total en el segundo paso cuando corresponde.',
  ),
  'pre_complex': StageScript(
    'i²=−1; el conjugado cambia solo la parte imaginaria y el módulo es no negativo.',
    'Distribuye el producto, reemplaza i² y comprueba las partes real e imaginaria.',
    'Okabe puede dramatizarlo, pero i no es magia: cumple i²=−1. Ese detalle convierte el producto de conjugados en un real.',
    'Yukki, el diario conserva la parte real al conjugar. Solo cambia el signo de la parte imaginaria.',
    '¡Nueva coordenada para el episodio! Kei separa la parte real de la imaginaria antes de multiplicar.',
    'El plan usa el conjugado para limpiar el denominador. Karane revisa que no cambiemos también el signo real.',
    '¡Que no haya raíces reales no significa que no haya raíces complejas! Usa i y comprueba los dos signos.',
  ),
  'pre_limits': StageScript(
    'Un límite estudia valores cercanos; 0/0 es una indeterminación y los laterales deben coincidir.',
    'Compara los límites laterales y separa el límite del valor definido en el punto.',
    'El laboratorio estudia qué ocurre al acercarse. El valor exacto en el punto puede faltar y aun así existir un límite.',
    'Yukki, el diario observa desde ambos lados. No promediamos dos predicciones distintas para inventar un límite.',
    '¡La escena puede acercarse a un hueco! Kei mira el comportamiento cercano; eso es distinto de estar exactamente en el punto.',
    'Mi estrategia factoriza cuando aparece 0/0 y luego estudia la expresión equivalente cerca del punto, sin incluirlo por descuido.',
    '¡0/0 no es cero! Detén la sustitución, simplifica si procede y revisa qué valor se aproxima.',
  ),
  'pre_modeling': StageScript(
    'Una solución algebraica puede quedar fuera del dominio físico o interpretar otra cantidad.',
    'Comprueba la respuesta en el modelo y sus restricciones de tiempo, longitud o cantidad.',
    'Quiero un modelo que pueda comprobarse, investigador. Okabe puede bautizarlo; tú define qué representa cada variable y su unidad.',
    'Yukki, la predicción tiene contexto. En mi diario una longitud negativa no sirve como ancho de un rectángulo.',
    '¡El problema es el guion completo! Kei revisa qué cantidad pide y Takuya comprueba que nuestra respuesta pertenezca a esa escena.',
    'Mi plan conecta funciones, sucesiones y ecuaciones según el fenómeno. Karane comprueba la respuesta en el modelo elegido.',
    '¡No marques una raíz solo porque salió de la fórmula! Mira si puede representar la medida que pide el problema.',
  ),
  'lin_vectors': StageScript(
    'El producto escalar devuelve un número; el vectorial devuelve un vector y depende del orden.',
    'Comprueba componentes, norma y dirección según la operación solicitada.',
    'En el laboratorio las componentes guardan dirección y magnitud. Daru no debe confundir el producto escalar con el vectorial.',
    'Yukki, un vector no es solo una cantidad: también apunta. Mi diario conservaría cada componente y su signo.',
    '¡Kei, dibuja las flechas desde el origen! Sumar sus componentes es distinto de comparar si son perpendiculares.',
    'Mi estrategia identifica primero la operación. Karane puede comprobar con un producto escalar si dos direcciones son ortogonales.',
    '¡u×v cambia de signo si inviertes el orden! No lo trates como una multiplicación de números que siempre conmutan.',
  ),
  'lin_matrices': StageScript(
    'Las dimensiones deben permitir el producto y AB no es en general BA.',
    'Comprueba fila por columna y el tamaño del resultado antes de comparar entradas.',
    'Daru leería estas tablas con índices. Una entrada de AB se obtiene de una fila de A y una columna de B, en ese orden.',
    'Yukki, cada casilla del diario tiene fila y columna. Cambiar su orden puede cambiar la predicción del producto.',
    '¡El reparto tiene filas y columnas! Kei mira la fila de la primera matriz; Takuya, la columna de la segunda.',
    'Mi plan primero comprueba tamaños compatibles. Karane no va a dejarme multiplicar tablas que no pueden encajar.',
    '¡No multipliques entrada por entrada si piden AB! Y no cambies el orden como si las matrices fueran números.',
  ),
  'lin_systems': StageScript(
    'El vector solución debe cumplir todas las ecuaciones; ecuaciones proporcionales pueden ser redundantes o contradictorias.',
    'Sustituye el vector en cada ecuación y clasifica si hay una, ninguna o infinitas soluciones.',
    'El laboratorio impone varias condiciones a la vez. Una pareja que cumple solo una ecuación todavía no es solución del sistema.',
    'Yukki, una predicción válida tiene que satisfacer todas las páginas del sistema. No podemos elegir solo la más cómoda.',
    '¡Todo el equipo debe estar de acuerdo! Kei comprueba una ecuación y Takuya la otra con el mismo vector.',
    'Mi estrategia compara ecuaciones completas. Karane, duplicar coeficientes pero cambiar el resultado puede crear una contradicción.',
    '¡Dos ecuaciones escritas no siempre aportan dos condiciones nuevas! Mira si son independientes antes de hablar de solución única.',
  ),
  'lin_gauss': StageScript(
    'Las operaciones de fila afectan también la columna aumentada; un pivote no equivale al número de filas.',
    'Lee pivotes y contradicciones en la forma escalonada antes de contar variables libres.',
    'Daru puede eliminar coeficientes, pero debe transformar también b. En el laboratorio cambiamos ecuaciones equivalentes, no solo una tabla bonita.',
    'Yukki, cuando una fila cambia, cambia toda su página. El término independiente no se queda quieto mientras eliminamos.',
    '¡Ordenamos el guion por escalones! Kei busca pivotes y Takuya comprueba si alguna fila exige 0 igual a un número no nulo.',
    'Mi plan elimina una variable por vez. Karane revisa la columna aumentada para que el sistema siga siendo equivalente.',
    '¡No olvides el último número de la fila! Si solo restas los coeficientes, inventas un sistema distinto.',
  ),
  'lin_determinants': StageScript(
    'Escalar toda una matriz n×n multiplica su determinante por cⁿ, no solo por c.',
    'Comprueba productos diagonales, orientación y efecto de las operaciones de fila.',
    'El determinante registra escala y orientación del experimento. Intercambiar dos filas cambia su signo, aunque Daru conserve los mismos números.',
    'Yukki, el diario puede registrar cuánto cambia el área con signo. Un determinante cero avisa que se pierde una dimensión.',
    '¡El escenario cambia de tamaño y orientación! Kei mira si giramos dos filas o si escalamos todas a la vez.',
    'Mi estrategia distingue escalar una fila de escalar la matriz entera. Karane contará cuántas filas reciben el factor.',
    '¡En una matriz 2×2, multiplicar todo por tres cambia el determinante por nueve! Son dos filas escaladas.',
  ),
  'lin_inverse': StageScript(
    'Una matriz cuadrada puede ser singular; la inversa de AB invierte el orden de los factores.',
    'Multiplica la candidata por la matriz original y comprueba que dé la identidad.',
    'Deshacer el experimento exige una verdadera inversa. Daru comprobaría AA^(-1)=I, no invertiría cada entrada por separado.',
    'Yukki, para deshacer dos páginas seguimos el orden inverso. Por eso la inversa de AB es B^(-1)A^(-1).',
    '¡Rebobinamos la escena en orden! Kei comprueba la identidad; una matriz con filas dependientes no tiene un rebobinado único.',
    'Mi plan recupera x con A^(-1)b solo si A tiene inversa. Karane, primero revisamos el determinante.',
    '¡B^(-1) va antes que A^(-1) al deshacer AB! Te lo repetiré las veces que haga falta, pero también quiero ver el producto de comprobación.',
  ),
  'lin_spaces': StageScript(
    'Contener cero es necesario, pero también hay que conservar suma y escala.',
    'Prueba el vector cero y comprueba cierre bajo suma y multiplicación por cualquier escalar.',
    'El laboratorio necesita reglas de cierre, no solo un dibujo de recta. Una traslación fuera del origen no es un subespacio.',
    'Yukki, la página del cero debe estar en el conjunto, pero también todas las combinaciones permitidas. Una sola prueba no completa el diario.',
    '¡Que haya muchos personajes no basta para formar este equipo! Kei prueba si sumar y escalar mantiene los vectores dentro.',
    'Mi plan comprueba tres requisitos. Karane puede empezar por cero y luego buscar un contraejemplo de cierre.',
    '¡No declares subespacio solo porque contiene el origen! Falta comprobar qué pasa al sumar y multiplicar por escalares.',
  ),
  'lin_basis': StageScript(
    'Una base debe generar el espacio sin redundancias; sus coordenadas siguen el orden de sus vectores.',
    'Reconstruye el vector con la combinación de la base y comprueba independencia.',
    'Daru puede describir los mismos datos en otra base. Cambian las coordenadas, no el vector; comprobarlo es reconstruir Bc.',
    'Yukki, dos páginas con instrucciones diferentes pueden describir el mismo vector. El diario debe indicar qué base usa cada coordenada.',
    '¡Un reparto sin personajes repetidos y con todas las direcciones! Kei revisa que la base genere sin redundancia.',
    'Mi estrategia escribe v como combinación de los vectores de la base. Karane conserva el orden de los coeficientes.',
    '¡Las coordenadas nuevas no se copian de las estándar! Resuelve Bc=v y reconstruye el vector para comprobar.',
  ),
  'lin_rank': StageScript(
    'Rango más nulidad usa el número de columnas, que es la dimensión del dominio.',
    'Comprueba que rango+nulidad=n y que el rango no exceda filas ni columnas.',
    'En el laboratorio contamos direcciones que sobreviven y las que llegan a cero. Daru debe sumar rango y nulidad sobre el dominio, no el codominio.',
    'Yukki, unas direcciones producen salidas y otras quedan en el núcleo. Mi diario cuenta ambas para recuperar la dimensión de entrada.',
    '¡Kei, contemos direcciones independientes! Las columnas repetidas no suben el rango solo por aparecer en otra casilla.',
    'Mi plan identifica cuántas variables entran y cuántos pivotes hay. Karane obtiene la nulidad por diferencia.',
    '¡Mira las columnas para rango-nulidad! Usar las filas como n te puede dar una dimensión imposible.',
  ),
  'lin_transformations': StageScript(
    'Una traslación no nula no es lineal y las imágenes de la base se escriben como columnas.',
    'Comprueba T(0)=0, la matriz por columnas y el orden de una composición.',
    'El laboratorio transforma vectores sin desplazar el origen. Las columnas son T(e₁), T(e₂): Daru no debe escribirlas como filas.',
    'Yukki, un mapa lineal conserva combinaciones de entradas. La página del cero tiene que terminar en cero.',
    '¡Cambiamos el escenario de las flechas! Kei coloca las imágenes de la base como columnas para describir toda la transformación.',
    'Mi estrategia aplica T primero y S después si dice S∘T. Karane verificará el orden en un vector sencillo.',
    '¡Que una fórmula tenga x e y no la hace lineal! Mira si mueve el origen y si conserva suma y escala.',
  ),
  'lin_orthogonality': StageScript(
    'La proyección divide por u·u; ortogonal no significa automáticamente unitario.',
    'Comprueba productos escalares cero y norma uno después de normalizar.',
    'En el laboratorio separamos componentes y residuo perpendicular. Gram–Schmidt resta proyecciones antes de normalizar.',
    'Yukki, el diario separa la parte que apunta con u de la que queda perpendicular. No son la misma página.',
    '¡Kei, primero separamos direcciones y luego ajustamos longitudes! Una flecha perpendicular todavía puede no tener norma uno.',
    'Mi plan resta la proyección y después divide por la norma. Karane revisa que el residuo realmente sea ortogonal.',
    '¡No normalices antes de quitar la proyección si sigues Gram–Schmidt! Y comprueba ambas cosas: ángulo y longitud.',
  ),
  'lin_least_squares': StageScript(
    'Un ajuste mínimo no hace exacto cada dato; el residuo debe ser ortogonal a las columnas.',
    'Comprueba Aᵀ(b−Ax)=0 y calcula el error cuadrático del ajuste.',
    'Las mediciones del laboratorio no siempre encajan exactamente. Daru minimiza el error total y comprueba la ortogonalidad del residuo.',
    'Yukki, el diario puede tener datos que no encajan en una recta exacta. La mejor predicción minimiza los errores cuadrados, no los esconde.',
    '¡Kei, ajustemos el guion a todas las observaciones! Pasar por un punto no garantiza ser la mejor recta del conjunto.',
    'Mi estrategia escucha todos los datos. Karane puede comprobar las ecuaciones normales antes de elegir el ajuste.',
    '¡No elijas una recta solo porque pasa por dos puntos! El tercer dato también aporta error al ajuste.',
  ),
  'lin_eigen': StageScript(
    'El vector cero no es autovector; las entradas fuera de diagonal no son por sí solas autovalores.',
    'Multiplica Av y comprueba que coincida con λv para un vector no nulo.',
    'El experimento conserva la dirección de un autovector, aunque cambie su magnitud. Daru comprueba Av=λv, con v distinto de cero.',
    'Yukki, esta predicción conserva una dirección: el diario compara Av y λv. No basta con que dos números se parezcan.',
    '¡La flecha puede crecer sin abandonar su línea! Kei comprueba qué factor la transforma y si realmente conserva dirección.',
    'Mi plan busca λ con el polinomio característico y después un vector no nulo. Karane no aceptará el vector cero como atajo.',
    '¡La entrada que está fuera de la diagonal no se vuelve autovalor por llamar la atención! Calcula o justifica el espectro.',
  ),
  'lin_diagonalization': StageScript(
    'Repetir un autovalor no garantiza suficientes autovectores independientes.',
    'Comprueba que P tenga una base de autovectores y que A=PDP^(-1).',
    'Daru escogería una base propia para simplificar potencias. El laboratorio exige suficientes autovectores independientes, no solo una lista de raíces.',
    'Yukki, cambiar la base simplifica las páginas repetidas de A^n. Para volver al diario original también necesitamos P^(-1).',
    '¡Un nuevo reparto puede simplificar toda la temporada! Kei comprueba que los autovectores formen una base antes de usar la diagonal.',
    'Mi estrategia calcula D^n y después vuelve con P y P^(-1). Karane, no olvidemos las matrices del cambio de base.',
    '¡Triangular no significa diagonalizable! Si solo hay una dirección propia en ℝ², no podemos inventar la segunda.',
  ),
};

/// Neutral course signatures can be recalled in introductions and farewells.
const courseSignatures = <int, Map<String, String>>{
  1: {
    'kurisu': 'En álgebra, nuestro laboratorio pasa de operaciones a factores que podemos reconstruir. Okabe pone el nombre; tú sostienes la prueba.',
    'yuno': 'El diario de álgebra une operaciones, letras y ecuaciones. Yukki vería que cada página prepara la siguiente. ♡',
    'kotoko': '¡Esta temporada de álgebra empieza con números y termina reconstruyendo polinomios! Takuya y Kei ya tienen los apuntes del club.',
    'hakari': 'Mi plan de álgebra conecta operaciones, variables y ecuaciones. Rentarou nos anima; Karane y yo comprobamos cada transformación.',
    'karane': '¡El álgebra necesita una base clara! Hakari, primero operaciones; después podemos jugar con letras sin perder las reglas.',
  },
  2: {
    'kurisu': 'La geometría de nuestro laboratorio pide medidas y unidades. No aceptaré un dibujo de Okabe como sustituto de una comprobación.',
    'yuno': 'En el diario de geometría, Yukki puede ver giros, bordes, superficies y espacio. A cada medida le guardamos su unidad.',
    'kotoko': '¡Geometría cambia el escenario del club! Kei dibuja figuras y Takuya comprueba qué estamos midiendo.',
    'hakari': 'Mi estrategia de geometría distingue recorrer, cubrir y llenar. Karane vigila que no confundamos longitud, área y volumen.',
    'karane': '¡En geometría, un resultado también necesita su unidad! Hakari puede decorar el dibujo después de que las medidas cuadren.',
  },
  3: {
    'kurisu': 'Precálculo conecta entradas, curvas y comportamientos cercanos. El laboratorio de Okabe necesita modelos comprobables antes del cálculo.',
    'yuno': 'El diario de precálculo estudia funciones y cómo cambian. Yukki no adivina el futuro: lo explora con dominios, modelos y límites.',
    'kotoko': '¡Precálculo es una temporada de conexiones! Takuya, Kei: funciones, gráficas y modelos cuentan distintas partes de la misma historia.',
    'hakari': 'El plan de precálculo conecta fórmulas con gráficas y restricciones. Rentarou vería que avanzar también es saber dónde una regla funciona.',
    'karane': '¡En precálculo no basta con obtener un número! Hakari, también revisamos dominio, gráfica y contexto antes del desafío.',
  },
  4: {
    'kurisu': 'Trigonometría conecta ángulos y razones. Daru puede usar calculadora, pero nuestro laboratorio primero identifica lados y unidades.',
    'yuno': 'En el diario trigonométrico, Yukki sigue un ángulo desde el triángulo hasta el círculo y las alturas. Conservamos signos y unidades.',
    'kotoko': '¡Trigonometría cambia la cámara del episodio! Kei marca el ángulo y Takuya sigue sus razones hasta el círculo.',
    'hakari': 'Mi estrategia trigonométrica elige el ángulo de referencia antes de la fórmula. Karane comprueba si hablamos de grados o radianes.',
    'karane': '¡Primero el ángulo, luego los lados y después la razón! Hakari no me va a distraer de ese orden en trigonometría.',
  },
  5: {
    'kurisu': 'Los logaritmos buscan exponentes y ponen condiciones. Ni siquiera una operación bautizada por Okabe admite una base uno.',
    'yuno': 'El diario de logaritmos recupera exponentes sin olvidar las entradas permitidas. Yukki comprobaría la predicción elevando la base.',
    'kotoko': '¡En logaritmos buscamos el nivel escondido! Takuya, no es el resultado de la potencia: es el exponente que lo produce.',
    'hakari': 'Mi plan logarítmico deshace potencias y verifica dominio. Karane me recuerda que una suma no se separa como un producto.',
    'karane': '¡En logaritmos, las condiciones van primero! Rentarou puede animarte, pero no hará válido un argumento no positivo.',
  },
  6: {
    'kurisu': 'Nuestro curso de potencias amplía exponentes a cocientes, recíprocos y raíces. Daru tiene que respetar cuándo cada regla es válida.',
    'yuno': 'En el diario de potencias, Yukki puede pasar de factores repetidos a raíces. Cada nueva regla conserva sus condiciones.',
    'kotoko': '¡Esta temporada de potencias cambia cómo escribimos una operación! Kei revisa exponentes negativos y Takuya las raíces.',
    'hakari': 'El plan de potencias distingue signo de base, signo de exponente y tipo de operación. Karane no deja que los mezclemos.',
    'karane': '¡Potencias no es multiplicar siempre por el mismo número! Revisa si toca sumar, restar o multiplicar exponentes.',
  },
  7: {
    'kurisu': 'Segundo grado exige un diagnóstico y una comprobación: factores o fórmula general, discriminante y raíces. Ese es el protocolo del laboratorio.',
    'yuno': 'El diario de segundo grado puede guardar dos soluciones. Yukki revisaría ambas y después el contexto del problema.',
    'kotoko': '¡Segundo grado tiene más de un camino de solución! Kei y Takuya comprueban factores, fórmula y raíces antes del final.',
    'hakari': 'Mi plan para segundo grado cambia de método según la ecuación. Karane se asegura de que no olvidemos un signo ni una raíz.',
    'karane': '¡En segundo grado no estamos adivinando la x! Elige un método, úsalo bien y comprueba cada solución.',
  },
  8: {
    'kurisu': 'Álgebra lineal organiza direcciones, sistemas y transformaciones. Daru verá matrices; nuestro laboratorio también tiene que entender qué representan.',
    'yuno': 'El diario de álgebra lineal sigue vectores y sus transformaciones. Yukki puede comprobar sus predicciones con sistemas, proyecciones y pares propios.',
    'kotoko': '¡Álgebra lineal es el trabajo de todo el equipo de direcciones! Kei y Takuya pasan de matrices a bases y autovectores.',
    'hakari': 'Mi estrategia de álgebra lineal une cálculo matricial y significado geométrico. Karane no me deja perder el orden al componer transformaciones.',
    'karane': '¡Matrices, bases y autovalores no son listas para memorizar! Hakari, quiero ver qué transformación hace cada cálculo.',
  },
};
