import 'practice_bank.dart';
import 'course_models.dart';

const trigonometryLessons = [
  Lesson(
    'trig_sides',
    'El triángulo rectángulo',
    'Mira desde el ángulo',
    '△',
    'La hipotenusa está frente al ángulo recto y es el lado más largo. Para un ángulo agudo θ, el cateto opuesto está enfrente de θ; el adyacente toca θ y no es la hipotenusa. Al cambiar al otro ángulo agudo, opuesto y adyacente intercambian sus nombres.',
    'Un triángulo rectángulo tiene lados AB = 3, BC = 4 y AC = 5. El ángulo recto está en B. Mira desde A.',
    [
      'AC está frente a B: es la hipotenusa, de longitud 5.',
      'BC está frente a A: es el cateto opuesto, de longitud 4.',
      'AB toca A sin ser hipotenusa: es el cateto adyacente, de longitud 3.',
    ],
    [
      Exercise(
        'ABC es rectángulo en B: AB = 3, BC = 4 y AC = 5. ¿Qué lado es opuesto al ángulo A?',
        ['AB', 'BC', 'AC'],
        1,
        'El lado opuesto no toca el vértice A.',
        'BC es el lado frente al ángulo A.',
        [
          'AB toca A: es el cateto adyacente.',
          '',
          'AC es la hipotenusa, frente al ángulo recto B.',
        ],
      ),
      Exercise(
        'En un triángulo rectángulo con lados 5, 12 y 13, ¿cuál es la hipotenusa?',
        ['13', '12', '5'],
        0,
        'Busca el lado más largo, frente al ángulo recto.',
        'La hipotenusa mide 13; 5² + 12² = 13².',
        [
          '',
          '12 es uno de los catetos, menor que 13.',
          '5 es el cateto menor.',
        ],
      ),
      Exercise(
        'Si miras desde el otro ángulo agudo, ¿qué ocurre con los catetos?',
        [
          'La hipotenusa cambia',
          'No cambian de nombre',
          'Opuesto y adyacente se intercambian',
        ],
        2,
        'Los nombres de los catetos dependen del ángulo de referencia.',
        'Al cambiar de ángulo agudo se intercambian opuesto y adyacente; la hipotenusa sigue siendo la misma.',
        [
          'La hipotenusa siempre está frente al ángulo de 90°.',
          'Los nombres opuesto y adyacente dependen del ángulo elegido.',
          '',
        ],
      ),
      ...extraTrigSides,
    ],
  ),
  Lesson(
    'trig_ratios',
    'Seno, coseno y tangente',
    'Tres razones, un ángulo',
    'sin',
    'Para un ángulo agudo θ: sen θ = opuesto/hipotenusa, cos θ = adyacente/hipotenusa y tan θ = opuesto/adyacente. Son razones sin unidades. En triángulos semejantes con el mismo ángulo, las razones no cambian aunque los lados crezcan.',
    'Respecto a θ, el opuesto mide 3, el adyacente 4 y la hipotenusa 5.',
    [
      'sen θ = 3/5 = 0,6.',
      'cos θ = 4/5 = 0,8.',
      'tan θ = 3/4 = 0,75. Cada razón usa una pareja distinta de lados.',
    ],
    [
      Exercise(
        'Opuesto = 5, adyacente = 12, hipotenusa = 13. ¿Cuánto vale sen θ?',
        ['12/13', '5/12', '5/13'],
        2,
        'El seno divide opuesto entre hipotenusa.',
        'sen θ = 5/13.',
        ['12/13 es el coseno.', '5/12 es la tangente.', ''],
      ),
      Exercise(
        'Opuesto = 6, adyacente = 8, hipotenusa = 10. ¿Cuánto vale cos θ?',
        ['0,8', '0,6', '0,75'],
        0,
        'El coseno divide adyacente entre hipotenusa.',
        'cos θ = 8/10 = 0,8.',
        ['', '6/10 es el seno.', '6/8 es la tangente.'],
      ),
      Exercise(
        'Opuesto = 3, adyacente = 4, hipotenusa = 5. ¿Cuánto vale tan θ?',
        ['4/3', '3/4', '3/5'],
        1,
        'La tangente usa los dos catetos: opuesto/adyacente.',
        'tan θ = 3/4.',
        [
          'Has invertido la razón.',
          '',
          '3/5 es el seno, que usa la hipotenusa.',
        ],
      ),
      ...extraTrigRatios,
    ],
  ),
  Lesson(
    'trig_radians',
    'Grados y radianes',
    'Dos formas de medir un giro',
    'π',
    'Una vuelta completa mide 360° o 2π radianes; media vuelta, 180° o π radianes. Convierte grados a radianes multiplicando por π/180. Convierte radianes a grados multiplicando por 180/π. El modo DEG/RAD de una calculadora debe coincidir con la unidad del ángulo.',
    'Convierte 60° a radianes.',
    [
      'Multiplica por π/180: 60 × π/180.',
      'Simplifica 60/180 = 1/3.',
      '60° = π/3 radianes. Comprueba que es un sexto de vuelta.',
    ],
    [
      Exercise(
        '¿Cuántos radianes son 90°?',
        ['π/2', 'π', '2π'],
        0,
        'Multiplica 90 por π/180.',
        '90 × π/180 = π/2 radianes.',
        ['', 'π equivale a 180°.', '2π equivale a 360°.'],
      ),
      Exercise(
        '¿Cuántos grados son π/6 radianes?',
        ['60°', '30°', '6°'],
        1,
        'Multiplica π/6 por 180/π.',
        '(π/6) × (180/π) = 180/6 = 30°.',
        [
          '60° corresponde a π/3.',
          '',
          'El denominador seis divide 180°, no representa seis grados.',
        ],
      ),
      Exercise(
        '¿Cuántos radianes son 270°?',
        ['3π', 'π/4', '3π/2'],
        2,
        '270/180 se simplifica a 3/2.',
        '270 × π/180 = 3π/2 radianes.',
        [
          '3π equivale a 540°: te falta dividir entre dos.',
          'π/4 equivale a 45°.',
          '',
        ],
      ),
      ...extraTrigRadians,
    ],
  ),
  Lesson(
    'trig_special',
    'Ángulos especiales',
    '30°, 45° y 60°',
    '45°',
    'Un triángulo 45°–45°–90° tiene lados proporcionales a 1, 1, √2. Uno de 30°–60°–90° tiene lados 1, √3, 2; el lado menor está frente a 30°. Así: sen 30° = 1/2; cos 60° = 1/2; sen 45° = cos 45° = √2/2 y tan 45° = 1.',
    'Halla sen 30° sin calculadora.',
    [
      'Usa el triángulo 30°–60°–90° con lados 1, √3, 2.',
      'El opuesto a 30° mide 1 y la hipotenusa 2.',
      'sen 30° = 1/2. No confundas el opuesto con el lado √3.',
    ],
    [
      Exercise(
        '¿Cuánto vale cos 60°?',
        ['√3/2', '1/2', '1'],
        1,
        'En el triángulo especial, el adyacente a 60° mide 1 y la hipotenusa 2.',
        'cos 60° = 1/2.',
        [
          '√3/2 es sen 60° y cos 30°.',
          '',
          'El coseno de 60° no es 1; 1 corresponde a 0°.',
        ],
      ),
      Exercise(
        '¿Cuánto vale tan 45°?',
        ['1', '√2/2', '0'],
        0,
        'Los dos catetos son iguales.',
        'tan 45° = 1/1 = 1.',
        [
          '',
          '√2/2 corresponde al seno y al coseno de 45°.',
          'El opuesto no mide cero en un triángulo 45°–45°–90°.',
        ],
      ),
      Exercise(
        '¿Cuánto vale sen 45°?',
        ['1/2', '√3/2', '√2/2'],
        2,
        'Divide 1 entre √2 y racionaliza.',
        'sen 45° = 1/√2 = √2/2.',
        ['1/2 es el seno de 30°.', '√3/2 es el seno de 60°.', ''],
      ),
      ...extraTrigSpecial,
    ],
  ),
  Lesson(
    'trig_circle',
    'Círculo unitario e identidades',
    'Más allá de 90°',
    '⊕',
    'En un círculo de radio 1, el punto de ángulo θ tiene coordenadas (cos θ, sen θ). Mide desde el eje x positivo en sentido antihorario. En el segundo cuadrante x es negativo e y positivo. Siempre sen² θ + cos² θ = 1. Además tan θ = sen θ/cos θ cuando cos θ ≠ 0; la tangente no está definida a 90° ni a 270°.',
    'Un ángulo agudo tiene sen θ = 3/5. Halla cos θ.',
    [
      'cos² θ = 1 − sen² θ = 1 − 9/25.',
      'cos² θ = 16/25.',
      'Como θ es agudo, cos θ es positivo: cos θ = 4/5.',
    ],
    [
      Exercise(
        '¿Qué coordenadas corresponden a 90° en el círculo unitario?',
        ['(1, 0)', '(0, −1)', '(0, 1)'],
        2,
        'Una cuarta vuelta desde la derecha llega arriba.',
        'cos 90° = 0 y sen 90° = 1: el punto es (0, 1).',
        ['(1, 0) corresponde a 0°.', '(0, −1) corresponde a 270°.', ''],
      ),
      Exercise(
        'En el segundo cuadrante, ¿qué signos tienen seno y coseno?',
        [
          'Seno positivo, coseno negativo',
          'Ambos positivos',
          'Seno negativo, coseno positivo',
        ],
        0,
        'El seno es la coordenada y; el coseno es la x.',
        'En el segundo cuadrante y > 0 y x < 0: seno positivo y coseno negativo.',
        [
          '',
          'Ambos son positivos en el primer cuadrante.',
          'Ese patrón corresponde al cuarto cuadrante.',
        ],
      ),
      Exercise(
        'θ es agudo y sen θ = 5/13. ¿Cuánto vale cos θ?',
        ['8/13', '12/13', '5/12'],
        1,
        'Usa cos² θ = 1 − 25/169 y toma la raíz positiva.',
        'cos² θ = 144/169; cos θ = 12/13.',
        [
          'No restes directamente 5 de 13: la identidad usa cuadrados.',
          '',
          '5/12 es la tangente para este ángulo.',
        ],
      ),
      ...extraTrigCircle,
    ],
  ),
  Lesson(
    'trig_applications',
    'Alturas y distancias',
    'Lleva las razones al mundo',
    '↗',
    'Dibuja un triángulo rectángulo y marca el ángulo de referencia. Con distancia horizontal d y ángulo de elevación θ, la altura sobre el nivel de observación es h = d × tan θ. Para una escalera de longitud L que forma θ con el suelo, h = L × sen θ. Añade la altura de los ojos si la medición parte de ellos.',
    'Desde el suelo, a 10 m de una torre, ves su cima con elevación de 45°. ¿Cuánto mide?',
    [
      'La altura es el opuesto y los 10 m horizontales son el adyacente.',
      'tan 45° = h/10; como tan 45° = 1, h = 10 × 1.',
      'La torre mide 10 m. La observación parte del suelo, así que no añadimos altura de ojos.',
    ],
    [
      Exercise(
        'Una escalera de 10 m forma 30° con el suelo. ¿Qué altura alcanza?',
        ['5 m', '10 m', '5√3 m'],
        0,
        'La escalera es la hipotenusa; usa sen 30° = 1/2.',
        'h = 10 × sen 30° = 10 × 1/2 = 5 m.',
        [
          '',
          '10 m es la longitud inclinada, no la altura vertical.',
          '5√3 m es la distancia horizontal, usando el coseno.',
        ],
      ),
      Exercise(
        'Desde el suelo, a 8 m de un árbol, la elevación a su cima es 45°. ¿Cuál es su altura?',
        ['4 m', '8 m', '8√2 m'],
        1,
        'La altura y la distancia horizontal se relacionan con la tangente.',
        'h = 8 × tan 45° = 8 m.',
        [
          'tan 45° vale 1, no 1/2.',
          '',
          '8√2 m es la distancia inclinada a la cima.',
        ],
      ),
      Exercise(
        'Tus ojos están a 1,5 m del suelo. A 6 m horizontales de una torre, ves su cima a 45°. ¿Cuál es la altura total?',
        ['6 m', '4,5 m', '7,5 m'],
        2,
        'Calcula la altura sobre tus ojos y luego añade 1,5 m.',
        'Sobre los ojos: 6 × tan 45° = 6 m. Total: 6 + 1,5 = 7,5 m.',
        [
          '6 m es solo la altura sobre el nivel de tus ojos.',
          'La altura de los ojos se suma, no se resta.',
          '',
        ],
      ),
      ...extraTrigApplications,
    ],
  ),
];
